"use client";
import {useState} from 'react';
import Link from 'next/link';
import {useLanguage} from './language-context';
import {SocialUpdates} from './social-updates';
import {BriefingView} from './briefing-view';
import {Card,Badge} from './ui';
import data from '@/data/nepal.json';
type Signal={id:string;title:string;titleEn:string;summary:string;summaryEn:string;url:string;date?:string;platform?:string;account?:string;impact?:string;impactEn?:string};
type LegalItem=Signal & {status:string;statusEn:string;businessImpact:string;businessImpactEn:string;actions:string[];actionsEn:string[]};
type Assessment={code:string;name:string;nameEn:string;score:number;summary:string;summaryEn:string};
export function NepalPortal({view}:{view:'overview'|'briefings'|'sources'|'people'|'compliance'|'archive'}){
 const {language}=useLanguage(),en=language==='en';const t=(zh:string,english:string)=>en?english:zh;
 const [query,setQuery]=useState(''),[category,setCategory]=useState('');
 const sources=data.sources.filter(s=>(!category||s.category===category)&&`${s.name} ${s.nameEn} ${s.platform} ${s.category}`.toLowerCase().includes(query.toLowerCase()));
 const titles={overview:['尼泊尔 ICT 情报总览','Nepal ICT overview'],briefings:['尼泊尔 ICT 双周观察','Nepal ICT Market Brief'],sources:['尼泊尔新闻与社媒信源','Nepal news & social sources'],people:['尼泊尔政府与监管监控','Nepal government & regulator monitor'],compliance:['尼泊尔营商合规与法律新闻','Nepal business compliance & legal news'],archive:['历史简报归档','Historical briefing archive']};
 const signals=[...data.signals,...data.telegram.items] as Signal[];
 const legalItems=data.legal.items as LegalItem[];
 const assessments=data.compliance.countries as Assessment[];
 const resources=<p><a href="../resources/Nepal_Media_Monitoring_with_News_Sources.xlsx" download>{t('下载媒体监控附件（Excel 原件）','Download monitoring workbook (original Excel)')}</a><span> · </span><a href="https://github.com/Adam123wu/nepal-ict-briefing/blob/main/skills/nepal-ict-briefing/SKILL.md" target="_blank" rel="noreferrer">{t('查看简报技能与更新规则','View briefing skill and update rules')}</a></p>;
 return <><div className="hero"><div><div className="eyebrow">NEPAL · ICT INTELLIGENCE</div><h1>{titles[view][en?1:0]}</h1><p>{t(data.report.period,data.report.periodEn)}</p>{view==='briefings'&&<p className="hero-deck">{t('通信市场 · 政策监管 · 竞争格局 · 商机研判','Telecom markets · Policy & regulation · Competition · Opportunities')}</p>}</div><Badge>🇳🇵 {t('尼泊尔','Nepal')}</Badge></div>
 {view==='sources'&&<Card className="card-pad"><h2>{t('监控关注点与附件','Monitoring focus and attachments')}</h2><p>{t('附件已合并为 12 类监控关注点；原有 11 个简报栏目保持不变。新增网站必须通过日期和内容核验后才能形成新闻。','The attachments inform 12 monitoring focus areas while the existing 11 briefing sections remain. New sources require date and content verification before publication.')}</p><div className="summary-list">{data.focus.map(f=><p key={f.id}>{t(f.label,f.labelEn)}</p>)}</div>{resources}<p className="section-sub">{t('每天 01:30 尼泊尔时间采集候选；每天 04:45 由 Codex 研究、翻译并发布。Codex 内容更新需电脑和应用运行；候选采集不等于新闻已更新。','Daily candidate collection at 01:30 Nepal time; Codex editorial research, translation and publication at 04:45. Codex needs the computer and app running; collection alone is not an editorial refresh.')}</p></Card>}
 {view==='overview'&&<><div className="grid kpi-grid">{[[t('当前信源','Sources'),data.sources.length],[t('新闻已核验','Reviewed news'),data.report.stats.news],[t('政府机构','Government offices'),data.people.length],[t('覆盖平台','Platforms'),new Set(data.sources.map(s=>s.platform)).size]].map(([label,n])=><Card className="card-pad" key={label}><div className="kpi-label">{label}</div><div className="kpi-value">{n}</div></Card>)}</div><Card className="card-pad"><h2>{t('当前进度','Current status')}</h2><p>{t(data.report.status,data.report.statusEn)}</p><div className="summary-list">{(en?data.report.summaryEn:data.report.summary).map(x=><p key={x}>{x}</p>)}</div><Link className="button" href="/briefings">{t('阅读本期完整简报','Read the current briefing')}</Link></Card><div className="grid two-col">{['通信监管','运营商','ISP','设备商','科技与设备媒体','主流媒体'].map(c=><Card className="card-pad" key={c}><h3>{en?(data.sources.find(s=>s.category===c)?.categoryEn||c):c}</h3><p>{data.sources.filter(s=>s.category===c&&s.platform==='Website').map(s=>s.nameEn).join(' · ')}</p></Card>)}</div></>}
 {view==='briefings'&&<><SocialUpdates signals={signals} en={en}/><p className="editorial-note">{t(data.report.status,data.report.statusEn)}</p><BriefingView countries={data.report.countries} language={language}/></>}
 {view==='sources'&&<><Card className="card-pad"><p>{t('官网可读取、账号归属核验、新闻内容核验是三个不同状态。失败和待扫描均保留记录。','Website access, account ownership and news verification are separate statuses. Failed and pending scans remain visible.')}</p><p>{t(data.telegram.coverageGap||'仅采集已核验的公开频道。',data.telegram.coverageGapEn||'Only verified public channels are collected.')}</p></Card><div className="table-tools"><input className="search" aria-label={t('搜索信源','Search sources')} placeholder={t('搜索媒体、机构、设备商或平台','Search sources and platforms')} value={query} onChange={e=>setQuery(e.target.value)}/><select className="select" aria-label={t('信源类型','Source category')} value={category} onChange={e=>setCategory(e.target.value)}><option value="">{t('全部类型','All categories')}</option>{Array.from(new Set(data.sources.map(s=>s.category))).map(c=><option key={c} value={c}>{en?data.sources.find(s=>s.category===c)?.categoryEn:c}</option>)}</select></div><Card className="table-card"><div className="table-wrap"><table className="data-table"><thead><tr>{[t('机构 / 媒体','Organization / publisher'),t('类型','Category'),t('平台','Platform'),t('扫描状态','Scan status'),t('归属依据','Ownership evidence')].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{sources.map(s=><tr key={s.id}><td><a href={s.url} target="_blank" rel="noreferrer">{t(s.name,s.nameEn)}</a><div className="section-sub">{s.tier} · 🇳🇵</div></td><td>{t(s.category,s.categoryEn)}</td><td>{s.platform}</td><td>{t(s.status,s.statusEn)}<div className="section-sub">{s.lastCollectedAt||t('尚未完成帖子扫描','Post scan not completed')}</div></td><td><a href={s.verificationUrl} target="_blank" rel="noreferrer">{t(s.verifiedBy,s.verifiedByEn)}</a></td></tr>)}</tbody></table></div></Card></>}
 {view==='people'&&<><p>{t('按机构和决策岗位建立监控；已核验姓名附官方出处；未确认的岗位和个人账号保留待核验状态。','Monitoring is organized by institution and decision-making office. Verified names link to official directories; unresolved offices and personal accounts stay explicitly unverified.')}</p><div className="grid two-col">{data.people.map(p=><Card className="card-pad" key={p.id}><h3>{t(p.name,p.nameEn)}</h3><p>{t(p.role,p.roleEn)}</p><Badge>{t(p.status,p.statusEn)}</Badge><p><a href={p.source} target="_blank" rel="noreferrer">{t('官方机构页面','Official institution page')}</a></p></Card>)}</div></>}
 {view==='compliance'&&<><Card className="card-pad"><h2>{t(data.compliance.status,data.compliance.statusEn)}</h2><p>{t(data.compliance.disclaimer,data.compliance.disclaimerEn)}</p><p>{t('评分维度：政治与监管20%、市场准入20%、廉洁透明15%、交易合规20%、ICT监管15%、采购清晰度10%。','Weights: political/regulatory stability 20%, market access 20%, integrity 15%, transaction compliance 20%, ICT regulation 15%, procurement clarity 10%.')}</p></Card><Card className="card-pad"><h2>{t(data.legal.title,data.legal.titleEn)}</h2><p>{t(data.legal.status,data.legal.statusEn)}</p><p>{t('重点：牌照、频谱、设备准入、政府采购、投资、税务、数字支付、数据与网络安全。','Focus: licensing, spectrum, equipment approval, procurement, investment, tax, digital payments, data and cybersecurity.')}</p><div className="grid two-col">{data.legal.sources.map(s=><a className="card card-pad" href={s.url} key={s.id} target="_blank" rel="noreferrer"><strong>{t(s.name,s.nameEn)}</strong><p>{t(s.category,s.categoryEn)} · {t(s.status,s.statusEn)}</p></a>)}</div><p className="section-sub">{t(data.legal.disclaimer,data.legal.disclaimerEn)}</p></Card></>}
 {view==='archive'&&<><p>{t('仅归档尼泊尔简报。当前期提供完整中英文在线阅读及中文静态副本。','Nepal reports only. The current issue has a bilingual online edition and a Chinese static copy.')}</p><div className="archive-list">{data.archive.map(i=><Card className="card-pad" key={i.file}><h3>{i.week} · {t('尼泊尔简报','Nepal briefing')}</h3><p>{t(i.date,data.report.periodEn)}</p><Link href="/briefings">{t('中英文在线版','Bilingual edition')}</Link><span> · </span><a href={`../archive/${i.file}`}>{t('中文静态副本','Chinese static copy')}</a></Card>)}</div></>}
 {view==='compliance'&&<>{assessments.map(c=><Card className="card-pad" key={c.code}><h2>{t(c.name,c.nameEn)} · {c.score.toFixed(1)} / 10</h2><p>{t(c.summary,c.summaryEn)}</p></Card>)}{legalItems.map(i=><Card className="card-pad" key={i.id}><Badge>{t(i.status,i.statusEn)}</Badge><h3>{t(i.title,i.titleEn)}</h3><p>{t(i.summary,i.summaryEn)}</p><p>{t(i.businessImpact,i.businessImpactEn)}</p><ul>{(en?i.actionsEn:i.actions).map(a=><li key={a}>{a}</li>)}</ul><a href={i.url} target="_blank" rel="noreferrer">{t('官方法律原文','Official legal text')}</a></Card>)}</>}
 </>;
}
