import fs from 'node:fs/promises';
const read=async p=>JSON.parse(await fs.readFile(p,'utf8'));
const save=(p,v)=>fs.writeFile(p,JSON.stringify(v,null,2)+'\n');
export async function syncNepal(){
 const market=await read('config/market.json');
 const focus=await read('config/monitoring-focus.json');
 const report=await read('config/nepal-report.json');
 const sources=await read('config/sources.json');
 const people=await read('config/nepal-people.json');
 const compliance=await read('config/compliance-analysis.json');
 const legal=await read('config/nepal-legal-news.json');
 const signals=await read('config/social-signals.json');
 const editorial=await read('config/editorial-status.json');
 const fallback=await read('config/deepseek-fallback-digest.json');
 const tracking=await read('config/tracked-topics.json');
 const trackingStatus=await read('config/tracking-state.json');
 const signalEn=await read('config/social-signal-translations-en.json');
 const raw=await read('config/telegram-feed.json');
 const zh=await read('config/telegram-translations.json'),en=await read('config/telegram-translations-en.json');
 for(const group of [sources,people,signals,raw.items])for(const item of group)if(item.country!=='尼泊尔')throw Error('Non-Nepal data in active inputs: '+(item.id||item.name));
 const social=signals.map(s=>{const e=signalEn[s.id];if(!e?.title||!e?.summary||!e?.impact)throw Error('Missing English signal: '+s.id);return {...s,titleEn:e.title,summaryEn:e.summary,impactEn:e.impact,accountEn:e.account};});
 const tg=raw.items.filter(i=>zh[i.id]?.title&&zh[i.id]?.summary&&en[i.id]?.title&&en[i.id]?.summary).map(i=>({...i,...zh[i.id],titleEn:en[i.id].title,summaryEn:en[i.id].summary,translationStatus:'双语已完成'}));
 const reviewed=new Set(social.flatMap(i=>i.sourceMessageIds||[]));
 const urls=new Set(social.map(i=>i.url));
 const feed={...raw,items:tg.filter(i=>!reviewed.has(i.id)&&!urls.has(i.url))};feed.messageCount=feed.items.length;
 const history=await read('config/history-reports.json');
 const items=report.countries.np.sections.flatMap(s=>s.items);
 report.stats={news:items.length,opportunities:items.filter(i=>i.opportunity).length,telegram:feed.items.length,countryCounts:{np:items.length}};
 await fs.mkdir('data',{recursive:true});
 const collected=await read('config/nepal-source-candidates.json');
 await save('data/refresh-status.json',{generatedAt:collected.generatedAt,candidateCount:collected.candidates.length,failedSources:sources.filter(s=>s.scanError).length});
 await save('data/report.json',report);await save('data/sources.json',sources);await save('data/people.json',people);
 await save('data/social-signals.json',social);await save('data/telegram-feed.json',feed);await save('data/compliance-analysis.json',compliance);
 await save('data/nepal-legal-news.json',legal);await save('data/history-reports.json',history);
 await save('data/editorial-status.json',editorial);await save('data/deepseek-fallback-digest.json',fallback);
 await save('data/tracking-status.json',trackingStatus);
 await save('data/nepal.json',{market,report,issues:[{...report,current:true},...history],sources,people,compliance,legal,signals:social,telegram:feed,editorial,fallback,tracking:{topics:tracking.topics.map(({id,reportItemId,title,titleEn,enabled})=>({id,reportItemId,title,titleEn,enabled})),status:trackingStatus},focus:focus.focusAreas.map(({id,label,labelEn,priority})=>({id,label,labelEn,priority}))});
 console.log(`Nepal: ${sources.length} sources, ${people.length} monitored offices; ${report.stats.news} reviewed news.`);
}
